version: '3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    hostname: "mongo"
    ports:
      - "27017:27017"

  selenium:
    image: selenium/standalone-firefox:4.19.1-20240402
    hostname: "selenium"
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - selenium
    hostname: scraper

